# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: true
    clientID: Ov23litwa9SWMh91LDoK # Default ClientID
    clientSecret: 49a40af3a73a701ef6112c63db1d005676c3fe89 # Default ClientSecret
    repo: junfenzhang1.github.io # The name of repository of store comments
    owner: junfenzhang1 # GitHub repo owner
    admin: junfenzhang1 # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy