# Avatar image
# avatar: /images/avatar.jpg
avatar: /images/avatar2.jpg

# Home page background image
background:
    - /images/background.jpg

# Loading image
loading: /images/loading.gif

# Optional colors for category and tag
colors:
    - "#ffa2c4"
    - "#00bcd4"
    - "#03a9f4"
    - "#00a596"
    - "#ff7d73"

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com

# Main menu navigation
menu:
    Home:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags

# Side info card
card:
    enable: true
    description: |
        Description
        ...
    iconLinks:
    friendLinks:
        Argvchs: https://argvchs.github.io

# Footer info
footer:
    since: 2022
    # Customize the server domain name ICP
    ICP:
        enable: false
        code:
        link:

# Polyfill
# https://polyfill.io
polyfill:
    enable: true
    features:
        - default

# Highlight.js
# https://highlightjs.org
highlight:
    enable: true
    style: github

# KaTeX math rendering
math:
    enable: false

# Image preview
preview:
    enable: true

# giscus
# https://github.com/giscus/giscus
giscus:
    enable: true
    src: "https://giscus.app/client.js"
    repo: "JunfenZhang1/junfenzhang1.github.io"
    repoID: "R_kgDONi3qdg"
    category: "Announcements"
    categoryID: "DIC_kwDONi3qds4Cljk1"
    mapping: "pathname"
    strict: "0"
    reactions-enabled: "1"
    emit-metadata: "0"
    input-position: "bottom"
    theme: "preferred_color_scheme"
    lang: "zh-CN"

# https://github.com/gitalk/gitalk
# gitalk:
#   enable: true
#   clientID: Ov23liw0H2FBurvN7cjK # Default ClientID
#   clientSecret: 467e85dd7c7e863977fd08fc93368a2000b3d6a4 # Default ClientSecret
#   repo: junfenzhang1.github.io # The name of repository of store comments
#   owner: JunfenZhang1 # GitHub repo owner
#   admin: JunfenZhang1 # GitHub repo owner and collaborators, only these guys can initialize github issues
#   language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
#   labels: 'gitalk' #github issue 对应的issue标签（新建一个）
#   distractionFreeMode: true  #无干扰模式，不需要更改
