# giscus
# https://github.com/giscus/giscus
# giscus:
#     enable: true
#     src: "https://giscus.app/client.js"
#     repo: "JunfenZhang1/junfenzhang1.github.io"
#     repo_id: "R_kgDONi3qdg"
#     category: "Announcements"
#     category_id: "DIC_kwDONi3qds4Cljk1"
#     mapping: "pathname"
#     strict: "0"
#     reactions-enabled: "1"
#     emit-metadata: "0"
#     input-position: "bottom"
#     theme: "preferred_color_scheme"
#     lang: "zh-CN"

# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  clientID: Ov23liw0H2FBurvN7cjK # Default ClientID
  clientSecret: 467e85dd7c7e863977fd08fc93368a2000b3d6a4 # Default ClientSecret
  repo: junfenzhang1.github.io # The name of repository of store comments
  github_id: JunfenZhang1 # GitHub repo owner
  admin_user: JunfenZhang1 # GitHub repo owner and collaborators, only these guys can initialize github issues
  language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
  distractionFreeMode: true  #无干扰模式，不需要更改

# Schemes
# scheme: Muse
# scheme: Mist
scheme: Pisces
# scheme: Gemini